spring:
  data:
    mongodb:
      uri: mongodb+srv://vineet:3Cfp3Zw1B9a57Tsa@cluster0.3c8gqrp.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
  servlet:
    context-path: /journal
